### ISSUE TITLE
Q: How do you automate installation of needed packages in ~/.blah-templates or ./.blah?

### ISSUE THREAD

**Issue by silviubogan** [IonicaBizau/dotfiles#50]
Did you ever automate this, or you always manually installed each package, such as `json2md` (required from [README.ejs][1]) using npm, like this:?

```sh
cd ~/.blah-templates
mkdir node_modules
npm i json2md [...]
```

  [1]: https://github.com/IonicaBizau/dotfiles/blob/master/blah-templates/README.ejs#L24

**Comment by IonicaBizau** [comment]
There is a `package.json` in `blah-templates`. Usually, I symlink the `~/.blah-templates` with the `blah-templates` from a clone of this repo.

Then: `cd path/to/dotfiles && npm i`
